[package]
name = "bouncer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bouncer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rapier3d = "0.17.2"