[package]
name = "bouncer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bouncer"
# crate-type = ["cdylib"], the Rust compiler generates a dynamic library that is loadable at runtime. 
# This is useful when you want to create a library that can be used by other languages, such as C or Python.
# crate-type = ["cdylib"]
path = "src/lib.rs"

[[bin]]
name = "bouncer"
path = "src/main.rs"

[dependencies]
pyo3 = "0.19.0"
rapier3d = "0.17.2"
